### ISSUE TITLE
Scrolling issue when you have a lot of content on the console

### ISSUE THREAD

**Issue by AleCaste** [marcominetti/node-console#1]
Excellent module!
I have an issue though, when you type a lot of content on the console or you try to display the value of a big object etc...
Basically when there are more lines on the console than the window size can display, you will NOT get scrollbars that would help you to see the whole lot.
To fix this issue I have included the following css rule on `front-end/inspectorCommon.css`:

```
html /deep/ .platform-windows > .view.vbox {
  overflow: auto;
}
```

This rule fixes the problem. Maybe there is a better way, I don't know.
In any case I hope you can fix the problem one way or another to include it on a future release.
Alex

**Comment by marcominetti** [comment]
Thanks @AleCaste

**Comment by marcominetti** [comment]
Done, I'm going to add autoscroll in next release.

**Comment by marcominetti** [comment]
Fixed to me. Please confirm.
